tap "oven-sh/bun"
tap "gromgit/brewtils"

brew "gromgit/brewtils/taproom"
brew "bat"
brew "delta"
brew "oven-sh/bun/bun"
brew "direnv"
brew "fd"
brew "fzf"
brew "gh"
brew "git-lfs" if OS.mac?
brew "jq"
brew "just"
brew "pre-commit"
brew "hyperfine"
brew "ripgrep"
brew "ruff"
brew "shellcheck"
brew "shfmt"
brew "starship"
brew "stylua"
brew "yamlfmt"
brew "mdformat"
brew "uv"
brew "yazi"
brew "yq"
brew "zoxide"
brew "ddcutil" if OS.linux?
brew "bash-completion@2"
brew "fzf-tab"
brew "zsh-autosuggestions"
brew "zsh-fast-syntax-highlighting"

cask "claude-code"
cask "claude" if OS.mac?
cask "font-sf-pro" if OS.mac?
cask "font-et-book"
cask "font-symbols-only-nerd-font"
cask "font-cascadia-code"
cask "font-inter"
cask "font-selawik"
cask "font-source-code-pro"
