vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
end
vim.g.colors_name = "eccentric-dark"
vim.o.background = "dark"

local hl = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
end

-- terminal colors (brights derived from normals via OKLCH lightness offset)
vim.g.terminal_color_0 = "#5f6672"
vim.g.terminal_color_1 = "#e06c75"
vim.g.terminal_color_2 = "#98c379"
vim.g.terminal_color_3 = "#e5c07b"
vim.g.terminal_color_4 = "#61afef"
vim.g.terminal_color_5 = "#b57edc"
vim.g.terminal_color_6 = "#56b6c2"
vim.g.terminal_color_7 = "#a9b2c3"
vim.g.terminal_color_8 = "#707784"
vim.g.terminal_color_9 = "#f57f87"
vim.g.terminal_color_10 = "#abd78c"
vim.g.terminal_color_11 = "#f9d38e"
vim.g.terminal_color_12 = "#74c2ff"
vim.g.terminal_color_13 = "#c891f0"
vim.g.terminal_color_14 = "#6ac9d5"
vim.g.terminal_color_15 = "#bcc5d6"

-- base UI
hl("Normal", { fg = "#a9b2c3", bg = "#181a1f" })
hl("NormalFloat", { fg = "#a9b2c3", bg = "#21252b" })
hl("NormalNC", { fg = "#a9b2c3", bg = "#181a1f" })
hl("FloatBorder", { fg = "#1085ff", bg = "#21252b" })
hl("Cursor", { fg = "#181a1f", bg = "#a9b2c3" })
hl("CursorLine", { bg = "#2a2f36" })
hl("CursorLineNr", { fg = "#c6ccd7", bold = true })
hl("LineNr", { fg = "#5f6672" })
hl("SignColumn", { bg = "#181a1f" })
hl("ColorColumn", { bg = "#21252b" })
hl("Visual", { bg = "#363b43" })
hl("Search", { fg = "#181a1f", bg = "#1085ff" })
hl("IncSearch", { fg = "#181a1f", bg = "#e5c07b" })
hl("Pmenu", { fg = "#a9b2c3", bg = "#21252b" })
hl("PmenuSel", { fg = "#c6ccd7", bg = "#30353d" })
hl("PmenuSbar", { bg = "#21252b" })
hl("PmenuThumb", { bg = "#5f6672" })
hl("StatusLine", { fg = "#a9b2c3", bg = "#181a1f" })
hl("StatusLineNC", { fg = "#5f6672", bg = "#21252b" })
hl("TabLine", { fg = "#5f6672", bg = "#21252b" })
hl("TabLineSel", { fg = "#c6ccd7", bg = "#181a1f" })
hl("TabLineFill", { bg = "#21252b" })
hl("WinSeparator", { fg = "#0d1117" })
hl("VertSplit", { fg = "#0d1117" })
hl("Folded", { fg = "#5f6672", bg = "#21252b" })
hl("FoldColumn", { fg = "#5f6672", bg = "#181a1f" })
hl("MatchParen", { fg = "#1085ff", bold = true })
hl("NonText", { fg = "#5f6672" })
hl("Whitespace", { fg = "#34393f" })
hl("EndOfBuffer", { fg = "#181a1f" })
hl("WildMenu", { fg = "#ffffff", bg = "#1085ff" })
hl("Title", { fg = "#e5c07b", bold = true })
hl("Directory", { fg = "#61afef" })
hl("ErrorMsg", { fg = "#d74e42" })
hl("WarningMsg", { fg = "#e9d16c" })
hl("MoreMsg", { fg = "#98c379" })
hl("Question", { fg = "#1085ff" })
hl("CurSearch", { fg = "#181a1f", bg = "#e5c07b" })
hl("QuickFixLine", { bg = "#2a2f36" })
hl("Conceal", { fg = "#5f6672" })
hl("SpecialKey", { fg = "#34393f" })
hl("WinBar", { fg = "#c6ccd7", bg = "#181a1f" })
hl("WinBarNC", { fg = "#5f6672", bg = "#181a1f" })
hl("FloatTitle", { fg = "#1085ff", bg = "#21252b", bold = true })
hl("SpellBad", { undercurl = true, sp = "#d74e42" })
hl("SpellCap", { undercurl = true, sp = "#e9d16c" })
hl("SpellLocal", { undercurl = true, sp = "#56b6c2" })
hl("SpellRare", { undercurl = true, sp = "#b57edc" })

-- syntax (keyword=red, storage=blue, function=lilac, type/tag=yellow, constant=cyan)
hl("Comment", { fg = "#5f6672" })
hl("Constant", { fg = "#56b6c2" })
hl("String", { fg = "#98c379" })
hl("Character", { fg = "#98c379" })
hl("Number", { fg = "#56b6c2" })
hl("Float", { fg = "#56b6c2" })
hl("Boolean", { fg = "#56b6c2" })
hl("Identifier", { fg = "#c6ccd7" })
hl("Function", { fg = "#b57edc" })
hl("Statement", { fg = "#e06c75" })
hl("Keyword", { fg = "#e06c75" })
hl("Conditional", { fg = "#e06c75" })
hl("Repeat", { fg = "#e06c75" })
hl("Label", { fg = "#e06c75" })
hl("Operator", { fg = "#a9b2c3" })
hl("Exception", { fg = "#e06c75" })
hl("PreProc", { fg = "#e06c75" })
hl("Include", { fg = "#e06c75" })
hl("Define", { fg = "#e06c75" })
hl("Macro", { fg = "#e06c75" })
hl("Type", { fg = "#e5c07b" })
hl("StorageClass", { fg = "#61afef" })
hl("Structure", { fg = "#61afef" })
hl("Typedef", { fg = "#61afef" })
hl("Special", { fg = "#56b6c2" })
hl("SpecialChar", { fg = "#56b6c2" })
hl("Tag", { fg = "#e5c07b" })
hl("Delimiter", { fg = "#a9b2c3" })
hl("SpecialComment", { fg = "#5f6672" })
hl("Error", { fg = "#d74e42", bold = true })
hl("Todo", { fg = "#e9d16c", bold = true })
hl("Underlined", { fg = "#1085ff", underline = true })

-- treesitter
hl("@comment", { link = "Comment" })
hl("@comment.documentation", { fg = "#5f6672" })
hl("@comment.error", { fg = "#d74e42", bold = true })
hl("@comment.warning", { fg = "#e9d16c", bold = true })
hl("@comment.todo", { fg = "#e9d16c", bold = true })
hl("@comment.note", { fg = "#1085ff", bold = true })
hl("@keyword", { fg = "#e06c75" })
hl("@keyword.function", { fg = "#61afef" })
hl("@keyword.return", { fg = "#e06c75" })
hl("@keyword.operator", { fg = "#e06c75" })
hl("@keyword.import", { fg = "#e06c75" })
hl("@keyword.conditional", { fg = "#e06c75" })
hl("@keyword.repeat", { fg = "#e06c75" })
hl("@keyword.exception", { fg = "#e06c75" })
hl("@keyword.modifier", { fg = "#61afef" })
hl("@keyword.type", { fg = "#61afef" })
hl("@string", { link = "String" })
hl("@string.escape", { fg = "#56b6c2" })
hl("@string.special", { fg = "#56b6c2" })
hl("@string.regexp", { fg = "#56b6c2" })
hl("@character", { fg = "#98c379" })
hl("@number", { link = "Number" })
hl("@number.float", { link = "Float" })
hl("@boolean", { link = "Boolean" })
hl("@constant", { fg = "#56b6c2" })
hl("@constant.builtin", { fg = "#56b6c2" })
hl("@constant.macro", { fg = "#56b6c2" })
hl("@variable", { fg = "#c6ccd7" })
hl("@variable.builtin", { fg = "#e06c75" })
hl("@variable.member", { fg = "#c6ccd7" })
hl("@variable.parameter", { fg = "#c6ccd7" })
hl("@function", { fg = "#b57edc" })
hl("@function.builtin", { fg = "#b57edc" })
hl("@function.call", { fg = "#b57edc" })
hl("@function.method", { fg = "#b57edc" })
hl("@function.method.call", { fg = "#b57edc" })
hl("@function.macro", { fg = "#b57edc" })
hl("@constructor", { fg = "#e5c07b" })
hl("@type", { fg = "#e5c07b" })
hl("@type.builtin", { fg = "#61afef" })
hl("@type.definition", { fg = "#e5c07b" })
hl("@type.qualifier", { fg = "#61afef" })
hl("@attribute", { fg = "#d19a66" })
hl("@property", { fg = "#c6ccd7" })
hl("@field", { fg = "#c6ccd7" })
hl("@operator", { fg = "#a9b2c3" })
hl("@punctuation.bracket", { fg = "#a9b2c3" })
hl("@punctuation.delimiter", { fg = "#a9b2c3" })
hl("@punctuation.special", { fg = "#a9b2c3" })
hl("@tag", { fg = "#e5c07b" })
hl("@tag.builtin", { fg = "#e5c07b" })
hl("@tag.attribute", { fg = "#d19a66" })
hl("@tag.delimiter", { fg = "#a9b2c3" })
hl("@label", { fg = "#e06c75" })
hl("@namespace", { fg = "#61afef" })
hl("@module", { fg = "#61afef" })

-- markup
hl("@markup.heading", { fg = "#e5c07b", bold = true })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.raw", { fg = "#98c379" })
hl("@markup.raw.block", { fg = "#98c379" })
hl("@markup.strikethrough", { strikethrough = true })
hl("@markup.link", { fg = "#1085ff", underline = true })
hl("@markup.link.label", { fg = "#e06c75" })
hl("@markup.link.url", { fg = "#1085ff", underline = true })
hl("@markup.list", { fg = "#a9b2c3" })
hl("@markup.quote", { fg = "#5f6672" })

-- diagnostics
hl("DiagnosticError", { fg = "#d74e42" })
hl("DiagnosticWarn", { fg = "#e9d16c" })
hl("DiagnosticInfo", { fg = "#1085ff" })
hl("DiagnosticHint", { fg = "#56b6c2" })
hl("DiagnosticUnderlineError", { undercurl = true, sp = "#d74e42" })
hl("DiagnosticUnderlineWarn", { undercurl = true, sp = "#e9d16c" })
hl("DiagnosticUnderlineInfo", { undercurl = true, sp = "#1085ff" })
hl("DiagnosticUnderlineHint", { undercurl = true, sp = "#56b6c2" })
hl("DiagnosticOk", { fg = "#98c379" })
hl("DiagnosticUnnecessary", { fg = "#5f6672", undercurl = true, sp = "#5f6672" })
hl("DiagnosticDeprecated", { strikethrough = true, sp = "#5f6672" })
hl("LspInlayHint", { fg = "#5f6672", bg = "#21252b" })
hl("LspReferenceText", { bg = "#2a2f36" })
hl("LspReferenceRead", { bg = "#2a2f36" })
hl("LspReferenceWrite", { bg = "#30353d" })

-- diff / git
hl("DiffAdd", { fg = "#98c379", bg = "#21252b" })
hl("DiffChange", { fg = "#d19a66", bg = "#21252b" })
hl("DiffDelete", { fg = "#e06c75", bg = "#21252b" })
hl("DiffText", { fg = "#1085ff", bg = "#21252b" })
hl("GitSignsAdd", { fg = "#98c379" })
hl("GitSignsChange", { fg = "#d19a66" })
hl("GitSignsDelete", { fg = "#e06c75" })
hl("Added", { fg = "#98c379" })
hl("Changed", { fg = "#d19a66" })
hl("Removed", { fg = "#e06c75" })
hl("@diff.plus", { link = "Added" })
hl("@diff.minus", { link = "Removed" })
hl("@diff.delta", { link = "Changed" })
