vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
end
vim.g.colors_name = "eccentric-light"
vim.o.background = "light"

local hl = function(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
end

-- terminal colors (upstream Primary ANSI: magenta/cyan alias to red/blue)
vim.g.terminal_color_0 = "#000000"
vim.g.terminal_color_1 = "#db4437"
vim.g.terminal_color_2 = "#0f9d58"
vim.g.terminal_color_3 = "#f4b400"
vim.g.terminal_color_4 = "#4285f4"
vim.g.terminal_color_5 = "#db4437"
vim.g.terminal_color_6 = "#4285f4"
vim.g.terminal_color_7 = "#bfbfbf"
vim.g.terminal_color_8 = "#000000"
vim.g.terminal_color_9 = "#db4437"
vim.g.terminal_color_10 = "#0f9d58"
vim.g.terminal_color_11 = "#f4b400"
vim.g.terminal_color_12 = "#4285f4"
vim.g.terminal_color_13 = "#4285f4"
vim.g.terminal_color_14 = "#0f9d58"
vim.g.terminal_color_15 = "#ffffff"

-- base UI
hl("Normal", { fg = "#202124", bg = "#ffffff" })
hl("NormalFloat", { fg = "#202124", bg = "#f8f9fa" })
hl("NormalNC", { fg = "#202124", bg = "#ffffff" })
hl("FloatBorder", { fg = "#4285f4", bg = "#f8f9fa" })
hl("Cursor", { fg = "#ffffff", bg = "#000000" })
hl("CursorLine", { bg = "#f1f3f4" })
hl("CursorLineNr", { fg = "#202124", bold = true })
hl("LineNr", { fg = "#9aa0a6" })
hl("SignColumn", { bg = "#ffffff" })
hl("ColorColumn", { bg = "#f8f9fa" })
hl("Visual", { bg = "#d2e3fc" })
hl("Search", { fg = "#202124", bg = "#fde293" })
hl("IncSearch", { fg = "#202124", bg = "#f4b400" })
hl("Pmenu", { fg = "#202124", bg = "#f8f9fa" })
hl("PmenuSel", { fg = "#202124", bg = "#d2e3fc" })
hl("PmenuSbar", { bg = "#f8f9fa" })
hl("PmenuThumb", { bg = "#9aa0a6" })
hl("StatusLine", { fg = "#202124", bg = "#ffffff" })
hl("StatusLineNC", { fg = "#9aa0a6", bg = "#f8f9fa" })
hl("TabLine", { fg = "#5f6368", bg = "#f8f9fa" })
hl("TabLineSel", { fg = "#202124", bg = "#ffffff" })
hl("TabLineFill", { bg = "#f8f9fa" })
hl("WinSeparator", { fg = "#dadce0" })
hl("VertSplit", { fg = "#dadce0" })
hl("Folded", { fg = "#5f6368", bg = "#f8f9fa" })
hl("FoldColumn", { fg = "#9aa0a6", bg = "#ffffff" })
hl("MatchParen", { fg = "#4285f4", bold = true })
hl("NonText", { fg = "#9aa0a6" })
hl("Whitespace", { fg = "#e8eaed" })
hl("EndOfBuffer", { fg = "#ffffff" })
hl("WildMenu", { fg = "#ffffff", bg = "#4285f4" })
hl("Title", { fg = "#f4b400", bold = true })
hl("Directory", { fg = "#4285f4" })
hl("ErrorMsg", { fg = "#db4437" })
hl("WarningMsg", { fg = "#f4b400" })
hl("MoreMsg", { fg = "#0f9d58" })
hl("Question", { fg = "#4285f4" })
hl("CurSearch", { fg = "#202124", bg = "#f4b400" })
hl("QuickFixLine", { bg = "#f1f3f4" })
hl("Conceal", { fg = "#9aa0a6" })
hl("SpecialKey", { fg = "#e8eaed" })
hl("WinBar", { fg = "#202124", bg = "#ffffff" })
hl("WinBarNC", { fg = "#9aa0a6", bg = "#ffffff" })
hl("FloatTitle", { fg = "#4285f4", bg = "#f8f9fa", bold = true })
hl("SpellBad", { undercurl = true, sp = "#db4437" })
hl("SpellCap", { undercurl = true, sp = "#f4b400" })
hl("SpellLocal", { undercurl = true, sp = "#4285f4" })
hl("SpellRare", { undercurl = true, sp = "#0f9d58" })

-- syntax (keyword=red, function/constant/storage=blue, type/tag=yellow, string=green)
hl("Comment", { fg = "#9aa0a6" })
hl("Constant", { fg = "#0081b6" })
hl("String", { fg = "#0f9d58" })
hl("Character", { fg = "#0f9d58" })
hl("Number", { fg = "#0081b6" })
hl("Float", { fg = "#0081b6" })
hl("Boolean", { fg = "#0081b6" })
hl("Identifier", { fg = "#202124" })
hl("Function", { fg = "#8e3b95" })
hl("Statement", { fg = "#db4437" })
hl("Keyword", { fg = "#db4437" })
hl("Conditional", { fg = "#db4437" })
hl("Repeat", { fg = "#db4437" })
hl("Label", { fg = "#db4437" })
hl("Operator", { fg = "#202124" })
hl("Exception", { fg = "#db4437" })
hl("PreProc", { fg = "#db4437" })
hl("Include", { fg = "#db4437" })
hl("Define", { fg = "#db4437" })
hl("Macro", { fg = "#db4437" })
hl("Type", { fg = "#f4b400" })
hl("StorageClass", { fg = "#4285f4" })
hl("Structure", { fg = "#4285f4" })
hl("Typedef", { fg = "#4285f4" })
hl("Special", { fg = "#0081b6" })
hl("SpecialChar", { fg = "#0081b6" })
hl("Tag", { fg = "#f4b400" })
hl("Delimiter", { fg = "#202124" })
hl("SpecialComment", { fg = "#5f6368" })
hl("Error", { fg = "#db4437", bold = true })
hl("Todo", { fg = "#f4b400", bold = true })
hl("Underlined", { fg = "#4285f4", underline = true })

-- treesitter
hl("@comment", { link = "Comment" })
hl("@comment.documentation", { fg = "#9aa0a6" })
hl("@comment.error", { fg = "#db4437", bold = true })
hl("@comment.warning", { fg = "#f4b400", bold = true })
hl("@comment.todo", { fg = "#f4b400", bold = true })
hl("@comment.note", { fg = "#4285f4", bold = true })
hl("@keyword", { fg = "#db4437" })
hl("@keyword.function", { fg = "#4285f4" })
hl("@keyword.return", { fg = "#db4437" })
hl("@keyword.operator", { fg = "#db4437" })
hl("@keyword.import", { fg = "#db4437" })
hl("@keyword.conditional", { fg = "#db4437" })
hl("@keyword.repeat", { fg = "#db4437" })
hl("@keyword.exception", { fg = "#db4437" })
hl("@keyword.modifier", { fg = "#4285f4" })
hl("@keyword.type", { fg = "#4285f4" })
hl("@string", { link = "String" })
hl("@string.escape", { fg = "#0081b6" })
hl("@string.special", { fg = "#0081b6" })
hl("@string.regexp", { fg = "#0081b6" })
hl("@character", { fg = "#0f9d58" })
hl("@number", { link = "Number" })
hl("@number.float", { link = "Float" })
hl("@boolean", { link = "Boolean" })
hl("@constant", { fg = "#0081b6" })
hl("@constant.builtin", { fg = "#0081b6" })
hl("@constant.macro", { fg = "#0081b6" })
hl("@variable", { fg = "#202124" })
hl("@variable.builtin", { fg = "#db4437" })
hl("@variable.member", { fg = "#202124" })
hl("@variable.parameter", { fg = "#202124" })
hl("@function", { fg = "#8e3b95" })
hl("@function.builtin", { fg = "#8e3b95" })
hl("@function.call", { fg = "#8e3b95" })
hl("@function.method", { fg = "#8e3b95" })
hl("@function.method.call", { fg = "#8e3b95" })
hl("@function.macro", { fg = "#8e3b95" })
hl("@constructor", { fg = "#f4b400" })
hl("@type", { fg = "#f4b400" })
hl("@type.builtin", { fg = "#4285f4" })
hl("@type.definition", { fg = "#f4b400" })
hl("@type.qualifier", { fg = "#4285f4" })
hl("@attribute", { fg = "#b75400" })
hl("@property", { fg = "#202124" })
hl("@field", { fg = "#202124" })
hl("@operator", { fg = "#202124" })
hl("@punctuation.bracket", { fg = "#202124" })
hl("@punctuation.delimiter", { fg = "#202124" })
hl("@punctuation.special", { fg = "#202124" })
hl("@tag", { fg = "#f4b400" })
hl("@tag.builtin", { fg = "#f4b400" })
hl("@tag.attribute", { fg = "#b75400" })
hl("@tag.delimiter", { fg = "#202124" })
hl("@label", { fg = "#db4437" })
hl("@namespace", { fg = "#4285f4" })
hl("@module", { fg = "#4285f4" })

-- markup
hl("@markup.heading", { fg = "#f4b400", bold = true })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.raw", { fg = "#0f9d58" })
hl("@markup.raw.block", { fg = "#0f9d58" })
hl("@markup.strikethrough", { strikethrough = true })
hl("@markup.link", { fg = "#4285f4", underline = true })
hl("@markup.link.label", { fg = "#db4437" })
hl("@markup.link.url", { fg = "#4285f4", underline = true })
hl("@markup.list", { fg = "#202124" })
hl("@markup.quote", { fg = "#5f6368" })

-- diagnostics
hl("DiagnosticError", { fg = "#db4437" })
hl("DiagnosticWarn", { fg = "#f4b400" })
hl("DiagnosticInfo", { fg = "#4285f4" })
hl("DiagnosticHint", { fg = "#5f6368" })
hl("DiagnosticUnderlineError", { undercurl = true, sp = "#db4437" })
hl("DiagnosticUnderlineWarn", { undercurl = true, sp = "#f4b400" })
hl("DiagnosticUnderlineInfo", { undercurl = true, sp = "#4285f4" })
hl("DiagnosticUnderlineHint", { undercurl = true, sp = "#5f6368" })
hl("DiagnosticOk", { fg = "#0f9d58" })
hl("DiagnosticUnnecessary", { fg = "#9aa0a6", undercurl = true, sp = "#9aa0a6" })
hl("DiagnosticDeprecated", { strikethrough = true, sp = "#9aa0a6" })
hl("LspInlayHint", { fg = "#9aa0a6", bg = "#f8f9fa" })
hl("LspReferenceText", { bg = "#f1f3f4" })
hl("LspReferenceRead", { bg = "#f1f3f4" })
hl("LspReferenceWrite", { bg = "#e8eaed" })

-- diff / git
hl("DiffAdd", { bg = "#e6f4ea" })
hl("DiffChange", { bg = "#fef7e0" })
hl("DiffDelete", { fg = "#db4437", bg = "#fce8e6" })
hl("DiffText", { fg = "#202124", bg = "#fde293" })
hl("GitSignsAdd", { fg = "#0f9d58" })
hl("GitSignsChange", { fg = "#f4b400" })
hl("GitSignsDelete", { fg = "#db4437" })
hl("Added", { fg = "#0f9d58" })
hl("Changed", { fg = "#f4b400" })
hl("Removed", { fg = "#db4437" })
hl("@diff.plus", { link = "Added" })
hl("@diff.minus", { link = "Removed" })
hl("@diff.delta", { link = "Changed" })
