# Gruvbox Light Soft
[colors]
foreground = "#282828"
background = "#f2e5bc"
cursor_bg = "#b57614"
cursor_border = "#b57614"
cursor_fg = "#f2e5bc"
selection_bg = "#d5c4a1"
selection_fg = "#282828"
ansi = [
  "#f2e5bc",
  "#9d0006",
  "#79740e",
  "#b57614",
  "#076678",
  "#8f3f71",
  "#427b58",
  "#282828",
]
brights = [
  "#7c6f64",
  "#9d0006",
  "#79740e",
  "#b57614",
  "#076678",
  "#8f3f71",
  "#427b58",
  "#282828",
]
