# Pierre Dark Soft
[colors]
foreground = "#d4d4d4"
background = "#171717"
cursor_bg = "#69b1ff"
cursor_border = "#69b1ff"
cursor_fg = "#171717"
selection_bg = "#1f3e5e"
selection_fg = "#d4d4d4"

ansi = [
  "#171717",
  "#ff2e3f",
  "#0dbe4e",
  "#ffca00",
  "#009fff",
  "#e130ac",
  "#08c0ef",
  "#bcbcbc",
]
brights = [
  "#171717",
  "#ff2e3f",
  "#86c427",
  "#ffca00",
  "#009fff",
  "#e130ac",
  "#08c0ef",
  "#bcbcbc",
]
