# Pierre Light Soft
[colors]
foreground = "#737373"
background = "#f7f7f7"
cursor_bg = "#009fff"
cursor_border = "#009fff"
cursor_fg = "#ffffff"
selection_bg = "#dfebff"
selection_fg = "#525252"

ansi = [
  "#1d1d1d",
  "#ff2e3f",
  "#0dbe4e",
  "#ffca00",
  "#009fff",
  "#e130ac",
  "#08c0ef",
  "#bcbcbc",
]
brights = [
  "#1d1d1d",
  "#ff2e3f",
  "#86c427",
  "#ffca00",
  "#009fff",
  "#e130ac",
  "#08c0ef",
  "#bcbcbc",
]
